apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Vacation Rentals 1.5

on:
  push:
    branches:
      - '**'
jobs:
  build:
    steps:
      - name: compile
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Building VacationRentals"
          echo mvn install -Dmaven.test.skip=true
  analyze:
    steps:
      - name: scan
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Analyzing"
  deploy-qa:
    needs: build
    environment: qa
    steps:
      - name: deploy
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Deploying VacationRentals with helm install vacation-rentals to qa"
          echo Connect to app at https://https://vacationrentals.qa:${{ vars.CONNECTION_PORT }}
  deploy-production:
    needs: deploy-qa
    environment: Production
    steps:
      - name: deploy
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "Deploying VacationRentals helm install vacation-rentals to production"
      - name: test bash
        uses: docker://bash
        run: |
          echo testing bash...

